In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sys
from pathlib import Path

In [3]:
sys.path.append(str(Path.cwd().parent))

from tables import create_results_table

In [5]:
url = "https://raw.githubusercontent.com/kkathait/D501_Final_Project/refs/heads/main/combined_data.csv"

results = create_results_table(url)

In [6]:
results

                Team  Wins  Losses  Draws  Games
0            Arsenal   154      56     56    266
1        Aston Villa   114      99     53    266
2        Bournemouth    61      78     51    190
3          Brentford    68      73     49    190
4           Brighton    90      89     87    266
5            Burnley    41      98     51    190
6            Chelsea   123      77     66    266
7     Crystal Palace    82     103     81    266
8            Everton    86     110     70    266
9             Fulham    63      83     44    190
10           Ipswich     4      24     10     38
11             Leeds    45      67     40    152
12         Leicester    67      85     38    190
13         Liverpool   165      43     58    266
14             Luton     6      24      8     38
15          Man City   182      41     43    266
16        Man United   127      74     65    266
17         Newcastle   107      96     63    266
18           Norwich    10      53     13     76
19     Nott'm Forest    48      65     39    152
20  Sheffield United    24      69     21    114
21       Southampton    44     106     40    190
22        Sunderland    14      12     12     38
23         Tottenham   115      99     52    266
24           Watford    14      47     15     76
25         West Brom     5      22     11     38
26          West Ham    91     114     61    266
27            Wolves    81     124     61    266

# Creating a points table for the games

In [7]:
results["Points"] = (3 * results["Wins"]) + results["Draws"]

results["Games"] = (results["Wins"] + results["Losses"] + results["Draws"])

results = results.sort_values("Games", ascending = False)

results

                Team  Wins  Losses  Draws  Games  Points
0            Arsenal   154      56     56    266     518
1        Aston Villa   114      99     53    266     395
6            Chelsea   123      77     66    266     435
4           Brighton    90      89     87    266     357
7     Crystal Palace    82     103     81    266     327
8            Everton    86     110     70    266     328
26          West Ham    91     114     61    266     334
27            Wolves    81     124     61    266     304
16        Man United   127      74     65    266     446
17         Newcastle   107      96     63    266     384
15          Man City   182      41     43    266     589
13         Liverpool   165      43     58    266     553
23         Tottenham   115      99     52    266     397
3          Brentford    68      73     49    190     253
21       Southampton    44     106     40    190     172
5            Burnley    41      98     51    190     174
2        Bournemouth    61      78     51    190     234
12         Leicester    67      85     38    190     239
9             Fulham    63      83     44    190     233
11             Leeds    45      67     40    152     175
19     Nott'm Forest    48      65     39    152     183
20  Sheffield United    24      69     21    114      93
24           Watford    14      47     15     76      57
18           Norwich    10      53     13     76      43
10           Ipswich     4      24     10     38      22
14             Luton     6      24      8     38      26
22        Sunderland    14      12     12     38      54
25         West Brom     5      22     11     38      26