In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
url = 'https://raw.githubusercontent.com/kkathait/D501_Final_Project/refs/heads/main/combined_data.csv'

df_premier = pd.read_csv(url)

In [4]:
teams = sorted(set(df_premier["HomeTeam"]) | set(df_premier["AwayTeam"]))

records = []

for team in teams:
    home_games = df_premier[df_premier["HomeTeam"] == team]
    
    home_wins = (home_games["FTR"] == "H").sum()
    home_losses = (home_games["FTR"] == "A").sum()
    home_draws = (home_games["FTR"] == "D").sum()
    
    away_games = df_premier[df_premier["AwayTeam"] == team]
    
    away_wins = (away_games["FTR"] == "A").sum()
    away_losses = (away_games["FTR"] == "H").sum()
    away_draws = (away_games["FTR"] == "D").sum()
    
    records.append({
        "Team": team,
        "Wins": home_wins + away_wins,
        "Losses": home_losses + away_losses,
        "Draws": home_draws + away_draws,
        "Games": home_wins + away_wins + home_losses + away_losses + home_draws + away_draws
    })

standings = pd.DataFrame(records)

standings = standings.sort_values("Games", ascending = False)

standings

                Team  Wins  Losses  Draws  Games
0            Arsenal   154      56     56    266
13         Liverpool   165      43     58    266
26          West Ham    91     114     61    266
23         Tottenham   115      99     52    266
17         Newcastle   107      96     63    266
16        Man United   127      74     65    266
15          Man City   182      41     43    266
1        Aston Villa   114      99     53    266
27            Wolves    81     124     61    266
8            Everton    86     110     70    266
7     Crystal Palace    82     103     81    266
6            Chelsea   123      77     66    266
4           Brighton    90      89     87    266
9             Fulham    63      83     44    190
3          Brentford    68      73     49    190
12         Leicester    67      85     38    190
5            Burnley    41      98     51    190
2        Bournemouth    61      78     51    190
21       Southampton    44     106     40    190
11             Leeds    45      67     40    152
19     Nott'm Forest    48      65     39    152
20  Sheffield United    24      69     21    114
24           Watford    14      47     15     76
18           Norwich    10      53     13     76
22        Sunderland    14      12     12     38
25         West Brom     5      22     11     38
10           Ipswich     4      24     10     38
14             Luton     6      24      8     38

In [5]:
standings["Points"] = (3 * standings["Wins"]) + standings["Draws"]

standings["Games"] = (standings["Wins"] + standings["Losses"] + standings["Draws"])

standings = standings.sort_values("Games", ascending = False)

standings

                Team  Wins  Losses  Draws  Games  Points
0            Arsenal   154      56     56    266     518
26          West Ham    91     114     61    266     334
23         Tottenham   115      99     52    266     397
17         Newcastle   107      96     63    266     384
16        Man United   127      74     65    266     446
15          Man City   182      41     43    266     589
1        Aston Villa   114      99     53    266     395
27            Wolves    81     124     61    266     304
8            Everton    86     110     70    266     328
7     Crystal Palace    82     103     81    266     327
6            Chelsea   123      77     66    266     435
4           Brighton    90      89     87    266     357
13         Liverpool   165      43     58    266     553
5            Burnley    41      98     51    190     174
21       Southampton    44     106     40    190     172
2        Bournemouth    61      78     51    190     234
3          Brentford    68      73     49    190     253
12         Leicester    67      85     38    190     239
9             Fulham    63      83     44    190     233
11             Leeds    45      67     40    152     175
19     Nott'm Forest    48      65     39    152     183
20  Sheffield United    24      69     21    114      93
24           Watford    14      47     15     76      57
18           Norwich    10      53     13     76      43
22        Sunderland    14      12     12     38      54
25         West Brom     5      22     11     38      26
10           Ipswich     4      24     10     38      22
14             Luton     6      24      8     38      26

In [6]:
#Calculate cards by referee

referee_cards = (
    df_premier
    .groupby("Referee")
    .agg(
        Home_Yellow_Cards=("HY", "sum"),
        Away_Yellow_Cards=("AY", "sum"),
        Home_Red_Cards=("HR", "sum"),
        Away_Red_Cards=("AR", "sum"),
        Games_Refereed=("Referee", "count")
    )
    .reset_index()
)

referee_cards

,Referee,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Games_Refereed
0,A Kitchen,11,8,0,0,6
1,A Madley,193,246,8,6,131
2,A Marriner,107,118,5,2,81
3,A Moss,1,3,0,0,1
4,A Taylor,363,384,16,12,206
5,C Kavanagh,250,298,10,8,153
6,C Pawson,281,300,9,7,155
7,D Bond,39,54,2,2,23
8,D Coote,189,204,5,8,100
9,D England,168,227,7,4,99
10,D Webb,2,5,0,0,2
11,F Hallam,5,8,0,0,5
12,G Scott,75,77,8,4,55
13,J Brooks,168,152,4,5,74
14,J Gillett,157,157,2,2,84
15,J Gillett,1,1,0,0,1
16,J Moss,108,102,1,7,74
17,J Smith,18,13,0,2,8
18,K Friend,111,97,5,5,68
19,K Kavanagh,1,2,0,0,1
20,L Mason,36,44,1,0,27
21,L Smith,21,20,1,2,10
22,M Atkinson,104,113,3,6,84
23,M Dean,148,135,4,8,78
24,M Donohue,13,15,0,0,5
25,M Oliver,309,333,9,14,194
26,M Salisbury,115,120,4,4,61
27,O Langford,1,0,0,0,1
28,O Oliver,3,2,0,0,1
29,P Bankes,191,262,6,8,115
30,P Tierney,238,262,10,8,140
31,R Jones,178,247,6,5,110
32,R Madley,4,5,0,1,2
33,R Welch,5,3,1,0,2
34,S Allison,11,8,0,0,4
35,S Attwell,278,309,4,16,150
36,S Barrott,106,136,2,1,62
37,S Hooper,215,271,7,3,130
38,S Scott,1,2,0,0,1
39,S Singh,2,3,0,0,1
40,T Bramall,88,115,3,6,52
41,T Harrington,79,93,3,2,48
42,T Kirk,8,8,2,1,6
43,T Robinson,88,116,1,2,49

In [7]:
#Calculate the average cards per game
referee_cards["Home_Yellow_Avg"] = (
    referee_cards["Home_Yellow_Cards"] /
    referee_cards["Games_Refereed"]
)

referee_cards["Away_Yellow_Avg"] = (
    referee_cards["Away_Yellow_Cards"] /
    referee_cards["Games_Refereed"]
)

referee_cards["Home_Red_Avg"] = (
    referee_cards["Home_Red_Cards"] /
    referee_cards["Games_Refereed"]
)

referee_cards["Away_Red_Avg"] = (
    referee_cards["Away_Red_Cards"] /
    referee_cards["Games_Refereed"]
)

referee_cards

,Referee,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Games_Refereed,Home_Yellow_Avg,Away_Yellow_Avg,Home_Red_Avg,Away_Red_Avg
0,A Kitchen,11,8,0,0,6,1.833333,1.333333,0.000000,0.000000
1,A Madley,193,246,8,6,131,1.473282,1.877863,0.061069,0.045802
2,A Marriner,107,118,5,2,81,1.320988,1.456790,0.061728,0.024691
3,A Moss,1,3,0,0,1,1.000000,3.000000,0.000000,0.000000
4,A Taylor,363,384,16,12,206,1.762136,1.864078,0.077670,0.058252
5,C Kavanagh,250,298,10,8,153,1.633987,1.947712,0.065359,0.052288
6,C Pawson,281,300,9,7,155,1.812903,1.935484,0.058065,0.045161
7,D Bond,39,54,2,2,23,1.695652,2.347826,0.086957,0.086957
8,D Coote,189,204,5,8,100,1.890000,2.040000,0.050000,0.080000
9,D England,168,227,7,4,99,1.696970,2.292929,0.070707,0.040404
10,D Webb,2,5,0,0,2,1.000000,2.500000,0.000000,0.000000
11,F Hallam,5,8,0,0,5,1.000000,1.600000,0.000000,0.000000
12,G Scott,75,77,8,4,55,1.363636,1.400000,0.145455,0.072727
13,J Brooks,168,152,4,5,74,2.270270,2.054054,0.054054,0.067568
14,J Gillett,157,157,2,2,84,1.869048,1.869048,0.023810,0.023810
15,J Gillett,1,1,0,0,1,1.000000,1.000000,0.000000,0.000000
16,J Moss,108,102,1,7,74,1.459459,1.378378,0.013514,0.094595
17,J Smith,18,13,0,2,8,2.250000,1.625000,0.000000,0.250000
18,K Friend,111,97,5,5,68,1.632353,1.426471,0.073529,0.073529
19,K Kavanagh,1,2,0,0,1,1.000000,2.000000,0.000000,0.000000
20,L Mason,36,44,1,0,27,1.333333,1.629630,0.037037,0.000000
21,L Smith,21,20,1,2,10,2.100000,2.000000,0.100000,0.200000
22,M Atkinson,104,113,3,6,84,1.238095,1.345238,0.035714,0.071429
23,M Dean,148,135,4,8,78,1.897436,1.730769,0.051282,0.102564
24,M Donohue,13,15,0,0,5,2.600000,3.000000,0.000000,0.000000
25,M Oliver,309,333,9,14,194,1.592784,1.716495,0.046392,0.072165
26,M Salisbury,115,120,4,4,61,1.885246,1.967213,0.065574,0.065574
27,O Langford,1,0,0,0,1,1.000000,0.000000,0.000000,0.000000
28,O Oliver,3,2,0,0,1,3.000000,2.000000,0.000000,0.000000
29,P Bankes,191,262,6,8,115,1.660870,2.278261,0.052174,0.069565
30,P Tierney,238,262,10,8,140,1.700000,1.871429,0.071429,0.057143
31,R Jones,178,247,6,5,110,1.618182,2.245455,0.054545,0.045455
32,R Madley,4,5,0,1,2,2.000000,2.500000,0.000000,0.500000
33,R Welch,5,3,1,0,2,2.500000,1.500000,0.500000,0.000000
34,S Allison,11,8,0,0,4,2.750000,2.000000,0.000000,0.000000
35,S Attwell,278,309,4,16,150,1.853333,2.060000,0.026667,0.106667
36,S Barrott,106,136,2,1,62,1.709677,2.193548,0.032258,0.016129
37,S Hooper,215,271,7,3,130,1.653846,2.084615,0.053846,0.023077
38,S Scott,1,2,0,0,1,1.000000,2.000000,0.000000,0.000000
39,S Singh,2,3,0,0,1,2.000000,3.000000,0.000000,0.000000
40,T Bramall,88,115,3,6,52,1.692308,2.211538,0.057692,0.115385
41,T Harrington,79,93,3,2,48,1.645833,1.937500,0.062500,0.041667
42,T Kirk,8,8,2,1,6,1.333333,1.333333,0.333333,0.166667
43,T Robinson,88,116,1,2,49,1.795918,2.367347,0.020408,0.040816

In [8]:
#Compare home vs. away cards
referee_cards["Yellow_Card_Difference"] = (
    referee_cards["Home_Yellow_Avg"] -
    referee_cards["Away_Yellow_Avg"]
)

referee_cards["Red_Card_Difference"] = (
    referee_cards["Home_Red_Avg"] -
    referee_cards["Away_Red_Avg"]
)

referee_cards.sort_values(
    "Yellow_Card_Difference",
    ascending=False
)

,Referee,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Games_Refereed,Home_Yellow_Avg,Away_Yellow_Avg,Home_Red_Avg,Away_Red_Avg,Yellow_Card_Difference,Red_Card_Difference
33,R Welch,5,3,1,0,2,2.500000,1.500000,0.500000,0.000000,1.000000,0.500000
28,O Oliver,3,2,0,0,1,3.000000,2.000000,0.000000,0.000000,1.000000,0.000000
27,O Langford,1,0,0,0,1,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000
34,S Allison,11,8,0,0,4,2.750000,2.000000,0.000000,0.000000,0.750000,0.000000
17,J Smith,18,13,0,2,8,2.250000,1.625000,0.000000,0.250000,0.625000,-0.250000
0,A Kitchen,11,8,0,0,6,1.833333,1.333333,0.000000,0.000000,0.500000,0.000000
13,J Brooks,168,152,4,5,74,2.270270,2.054054,0.054054,0.067568,0.216216,-0.013514
18,K Friend,111,97,5,5,68,1.632353,1.426471,0.073529,0.073529,0.205882,0.000000
23,M Dean,148,135,4,8,78,1.897436,1.730769,0.051282,0.102564,0.166667,-0.051282
21,L Smith,21,20,1,2,10,2.100000,2.000000,0.100000,0.200000,0.100000,-0.100000
16,J Moss,108,102,1,7,74,1.459459,1.378378,0.013514,0.094595,0.081081,-0.081081
42,T Kirk,8,8,2,1,6,1.333333,1.333333,0.333333,0.166667,0.000000,0.166667
14,J Gillett,157,157,2,2,84,1.869048,1.869048,0.023810,0.023810,0.000000,0.000000
15,J Gillett,1,1,0,0,1,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
12,G Scott,75,77,8,4,55,1.363636,1.400000,0.145455,0.072727,-0.036364,0.072727
26,M Salisbury,115,120,4,4,61,1.885246,1.967213,0.065574,0.065574,-0.081967,0.000000
4,A Taylor,363,384,16,12,206,1.762136,1.864078,0.077670,0.058252,-0.101942,0.019417
22,M Atkinson,104,113,3,6,84,1.238095,1.345238,0.035714,0.071429,-0.107143,-0.035714
6,C Pawson,281,300,9,7,155,1.812903,1.935484,0.058065,0.045161,-0.122581,0.012903
25,M Oliver,309,333,9,14,194,1.592784,1.716495,0.046392,0.072165,-0.123711,-0.025773
2,A Marriner,107,118,5,2,81,1.320988,1.456790,0.061728,0.024691,-0.135802,0.037037
8,D Coote,189,204,5,8,100,1.890000,2.040000,0.050000,0.080000,-0.150000,-0.030000
30,P Tierney,238,262,10,8,140,1.700000,1.871429,0.071429,0.057143,-0.171429,0.014286
35,S Attwell,278,309,4,16,150,1.853333,2.060000,0.026667,0.106667,-0.206667,-0.080000
41,T Harrington,79,93,3,2,48,1.645833,1.937500,0.062500,0.041667,-0.291667,0.020833
20,L Mason,36,44,1,0,27,1.333333,1.629630,0.037037,0.000000,-0.296296,0.037037
5,C Kavanagh,250,298,10,8,153,1.633987,1.947712,0.065359,0.052288,-0.313725,0.013072
24,M Donohue,13,15,0,0,5,2.600000,3.000000,0.000000,0.000000,-0.400000,0.000000
1,A Madley,193,246,8,6,131,1.473282,1.877863,0.061069,0.045802,-0.404580,0.015267
37,S Hooper,215,271,7,3,130,1.653846,2.084615,0.053846,0.023077,-0.430769,0.030769
36,S Barrott,106,136,2,1,62,1.709677,2.193548,0.032258,0.016129,-0.483871,0.016129
32,R Madley,4,5,0,1,2,2.000000,2.500000,0.000000,0.500000,-0.500000,-0.500000
40,T Bramall,88,115,3,6,52,1.692308,2.211538,0.057692,0.115385,-0.519231,-0.057692
43,T Robinson,88,116,1,2,49,1.795918,2.367347,0.020408,0.040816,-0.571429,-0.020408
9,D England,168,227,7,4,99,1.696970,2.292929,0.070707,0.040404,-0.595960,0.030303
11,F Hallam,5,8,0,0,5,1.000000,1.600000,0.000000,0.000000,-0.600000,0.000000
29,P Bankes,191,262,6,8,115,1.660870,2.278261,0.052174,0.069565,-0.617391,-0.017391
31,R Jones,178,247,6,5,110,1.618182,2.245455,0.054545,0.045455,-0.627273,0.009091
7,D Bond,39,54,2,2,23,1.695652,2.347826,0.086957,0.086957,-0.652174,0.000000
19,K Kavanagh,1,2,0,0,1,1.000000,2.000000,0.000000,0.000000,-1.000000,0.000000
38,S Scott,1,2,0,0,1,1.000000,2.000000,0.000000,0.000000,-1.000000,0.000000
39,S Singh,2,3,0,0,1,2.000000,3.000000,0.000000,0.000000,-1.000000,0.000000
10,D Webb,2,5,0,0,2,1.000000,2.500000,0.000000,0.000000,-1.500000,0.000000
3,A Moss,1,3,0,0,1,1.000000,3.000000,0.000000,0.000000,-2.000000,0.000000

In [9]:
#Find the referees with the biggest differences
referee_cards[
    [
        "Referee",
        "Games_Refereed",
        "Home_Yellow_Avg",
        "Away_Yellow_Avg",
        "Home_Red_Avg",
        "Away_Red_Avg",
        "Yellow_Card_Difference",
        "Red_Card_Difference"
    ]
].sort_values(
    "Yellow_Card_Difference",
    ascending=False
)

,Referee,Games_Refereed,Home_Yellow_Avg,Away_Yellow_Avg,Home_Red_Avg,Away_Red_Avg,Yellow_Card_Difference,Red_Card_Difference
33,R Welch,2,2.500000,1.500000,0.500000,0.000000,1.000000,0.500000
28,O Oliver,1,3.000000,2.000000,0.000000,0.000000,1.000000,0.000000
27,O Langford,1,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000
34,S Allison,4,2.750000,2.000000,0.000000,0.000000,0.750000,0.000000
17,J Smith,8,2.250000,1.625000,0.000000,0.250000,0.625000,-0.250000
0,A Kitchen,6,1.833333,1.333333,0.000000,0.000000,0.500000,0.000000
13,J Brooks,74,2.270270,2.054054,0.054054,0.067568,0.216216,-0.013514
18,K Friend,68,1.632353,1.426471,0.073529,0.073529,0.205882,0.000000
23,M Dean,78,1.897436,1.730769,0.051282,0.102564,0.166667,-0.051282
21,L Smith,10,2.100000,2.000000,0.100000,0.200000,0.100000,-0.100000
16,J Moss,74,1.459459,1.378378,0.013514,0.094595,0.081081,-0.081081
42,T Kirk,6,1.333333,1.333333,0.333333,0.166667,0.000000,0.166667
14,J Gillett,84,1.869048,1.869048,0.023810,0.023810,0.000000,0.000000
15,J Gillett,1,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
12,G Scott,55,1.363636,1.400000,0.145455,0.072727,-0.036364,0.072727
26,M Salisbury,61,1.885246,1.967213,0.065574,0.065574,-0.081967,0.000000
4,A Taylor,206,1.762136,1.864078,0.077670,0.058252,-0.101942,0.019417
22,M Atkinson,84,1.238095,1.345238,0.035714,0.071429,-0.107143,-0.035714
6,C Pawson,155,1.812903,1.935484,0.058065,0.045161,-0.122581,0.012903
25,M Oliver,194,1.592784,1.716495,0.046392,0.072165,-0.123711,-0.025773
2,A Marriner,81,1.320988,1.456790,0.061728,0.024691,-0.135802,0.037037
8,D Coote,100,1.890000,2.040000,0.050000,0.080000,-0.150000,-0.030000
30,P Tierney,140,1.700000,1.871429,0.071429,0.057143,-0.171429,0.014286
35,S Attwell,150,1.853333,2.060000,0.026667,0.106667,-0.206667,-0.080000
41,T Harrington,48,1.645833,1.937500,0.062500,0.041667,-0.291667,0.020833
20,L Mason,27,1.333333,1.629630,0.037037,0.000000,-0.296296,0.037037
5,C Kavanagh,153,1.633987,1.947712,0.065359,0.052288,-0.313725,0.013072
24,M Donohue,5,2.600000,3.000000,0.000000,0.000000,-0.400000,0.000000
1,A Madley,131,1.473282,1.877863,0.061069,0.045802,-0.404580,0.015267
37,S Hooper,130,1.653846,2.084615,0.053846,0.023077,-0.430769,0.030769
36,S Barrott,62,1.709677,2.193548,0.032258,0.016129,-0.483871,0.016129
32,R Madley,2,2.000000,2.500000,0.000000,0.500000,-0.500000,-0.500000
40,T Bramall,52,1.692308,2.211538,0.057692,0.115385,-0.519231,-0.057692
43,T Robinson,49,1.795918,2.367347,0.020408,0.040816,-0.571429,-0.020408
9,D England,99,1.696970,2.292929,0.070707,0.040404,-0.595960,0.030303
11,F Hallam,5,1.000000,1.600000,0.000000,0.000000,-0.600000,0.000000
29,P Bankes,115,1.660870,2.278261,0.052174,0.069565,-0.617391,-0.017391
31,R Jones,110,1.618182,2.245455,0.054545,0.045455,-0.627273,0.009091
7,D Bond,23,1.695652,2.347826,0.086957,0.086957,-0.652174,0.000000
19,K Kavanagh,1,1.000000,2.000000,0.000000,0.000000,-1.000000,0.000000
38,S Scott,1,1.000000,2.000000,0.000000,0.000000,-1.000000,0.000000
39,S Singh,1,2.000000,3.000000,0.000000,0.000000,-1.000000,0.000000
10,D Webb,2,1.000000,2.500000,0.000000,0.000000,-1.500000,0.000000
3,A Moss,1,1.000000,3.000000,0.000000,0.000000,-2.000000,0.000000

In [10]:
yellow_correlation = referee_cards[
    ["Home_Yellow_Avg", "Away_Yellow_Avg"]
].corr()

red_correlation = referee_cards[
    ["Home_Red_Avg", "Away_Red_Avg"]
].corr()

print("Yellow Card Correlation:")
print(yellow_correlation)

print("\nRed Card Correlation:")
print(red_correlation)

Yellow Card Correlation:
                 Home_Yellow_Avg  Away_Yellow_Avg
Home_Yellow_Avg          1.00000          0.29722
Away_Yellow_Avg          0.29722          1.00000

Red Card Correlation:
              Home_Red_Avg  Away_Red_Avg
Home_Red_Avg      1.000000      0.048785
Away_Red_Avg      0.048785      1.000000

In [11]:
import plotly.express as px

plot_data = referee_cards.melt(
    id_vars="Referee",
    value_vars=[
        "Home_Yellow_Avg",
        "Away_Yellow_Avg"
    ],
    var_name="Team_Location",
    value_name="Average_Yellow_Cards"
)

fig = px.bar(
    plot_data,
    x="Referee",
    y="Average_Yellow_Cards",
    color="Team_Location",
    barmode="group",
    title="Average Yellow Cards by Referee: Home vs. Away Teams"
)

fig.show()

In [14]:
#Is there a correlation between the number of cards a referee gives to the home team versus the away team?
referee_cards = (
    df_premier
    .groupby("Referee")
    .agg(
        Home_Yellow=("HY", "mean"),
        Away_Yellow=("AY", "mean"),
        Home_Red=("HR", "mean"),
        Away_Red=("AR", "mean")
    )
    .reset_index()
)

# Correlation between home and away yellow cards
yellow_corr = referee_cards["Home_Yellow"].corr(
    referee_cards["Away_Yellow"]
)

# Correlation between home and away red cards
red_corr = referee_cards["Home_Red"].corr(
    referee_cards["Away_Red"]
)

print("Yellow Card Correlation:", yellow_corr)
print("Red Card Correlation:", red_corr)

Yellow Card Correlation: 0.29721964021912095
Red Card Correlation: 0.048785418820572884

In [16]:
# combine yellow + red cards
df_premier["Home_Cards"] = df_premier["HY"] + df_premier["HR"]
df_premier["Away_Cards"] = df_premier["AY"] + df_premier["AR"]

referee_cards = (
    df_premier
    .groupby("Referee")
    .agg(
        Home_Cards=("Home_Cards", "mean"),
        Away_Cards=("Away_Cards", "mean")
    )
    .reset_index()
)

correlation = referee_cards["Home_Cards"].corr(
    referee_cards["Away_Cards"]
)

print("Correlation:", correlation)

Correlation: 0.2712791314700538

In [20]:
import plotly.express as px

df_premier["Home_Cards"] = df_premier["HY"] + df_premier["HR"]
df_premier["Away_Cards"] = df_premier["AY"] + df_premier["AR"]

referee_cards = (
    df_premier
    .groupby("Referee")
    .agg(
        Home_Cards=("Home_Cards", "mean"),
        Away_Cards=("Away_Cards", "mean")
    )
    .reset_index()
)

correlation = referee_cards["Home_Cards"].corr(
    referee_cards["Away_Cards"]
)

print("Correlation:", correlation)

fig = px.scatter(
    referee_cards,
    x="Home_Cards",
    y="Away_Cards",
    hover_name="Referee",
    title="Referee Cards: Home Team vs Away Team",
    labels={
        "Home_Cards": "Average Cards Given to Home Team",
        "Away_Cards": "Average Cards Given to Away Team"
    }
)

fig.show()

Correlation: 0.2712791314700538

In [21]:
import numpy as np
import plotly.graph_objects as go

x = referee_cards["Home_Cards"]
y = referee_cards["Away_Cards"]

slope, intercept = np.polyfit(x, y, 1)

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=x,
    y=y,
    mode="markers",
    text=referee_cards["Referee"],
    hovertemplate="%{text}<br>Home Cards: %{x:.2f}<br>Away Cards: %{y:.2f}<extra></extra>",
    name="Referees"
))

fig.add_trace(go.Scatter(
    x=x,
    y=slope * x + intercept,
    mode="lines",
    name="Trend Line"
))

fig.update_layout(
    title="Correlation Between Referee Cards Given to Home and Away Teams",
    xaxis_title="Average Cards Given to Home Team",
    yaxis_title="Average Cards Given to Away Team"
)

fig.show()

# Final Analysis

In [23]:
import pandas as pd
import numpy as np
import plotly.express as px

url = 'https://raw.githubusercontent.com/kkathait/D501_Final_Project/refs/heads/main/combined_data.csv'

df_premier = pd.read_csv(url)

# Goals
df_premier["Total_Goals"] = df_premier["FTHG"] + df_premier["FTAG"]

# Cards
df_premier["Home_Cards"] = df_premier["HY"] + df_premier["HR"]
df_premier["Away_Cards"] = df_premier["AY"] + df_premier["AR"]

df_premier["Total_Yellow_Cards"] = df_premier["HY"] + df_premier["AY"]
df_premier["Total_Red_Cards"] = df_premier["HR"] + df_premier["AR"]
df_premier["Total_Cards"] = (
    df_premier["Total_Yellow_Cards"] +
    df_premier["Total_Red_Cards"]
)

# Numerical result
df_premier["Home_Win"] = (df_premier["FTR"] == "H").astype(int)
df_premier["Away_Win"] = (df_premier["FTR"] == "A").astype(int)
df_premier["Draw"] = (df_premier["FTR"] == "D").astype(int)

df_premier.head()

/var/folders/dz/y62g61hn65n3bj60zmb7ppf00000gn/T/ipykernel_2157/796501320.py:10: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

/var/folders/dz/y62g61hn65n3bj60zmb7ppf00000gn/T/ipykernel_2157/796501320.py:13: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

/var/folders/dz/y62g61hn65n3bj60zmb7ppf00000gn/T/ipykernel_2157/796501320.py:14: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

/var/folders/dz/y62g61hn65n3bj60zmb7ppf00000gn/T/ipykernel_2157/796501320.py:16: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

/var/folders/dz/y62g61hn65n3bj60zmb7ppf00000gn/T/ipykernel_2157/796501320.py:17: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

/var/folders/dz/y62g61hn65n3bj60zmb7ppf00000gn/T/ipykernel_2157/796501320.py:18: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

/var/folders/dz/y62g61hn65n3bj60zmb7ppf00000gn/T/ipykernel_2157/796501320.py:24: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

/var/folders/dz/y62g61hn65n3bj60zmb7ppf00000gn/T/ipykernel_2157/796501320.py:25: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

/var/folders/dz/y62g61hn65n3bj60zmb7ppf00000gn/T/ipykernel_2157/796501320.py:26: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,VCCA,Total_Goals,Home_Cards,Away_Cards,Total_Yellow_Cards,Total_Red_Cards,Total_Cards,Home_Win,Away_Win,Draw
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,NaN,6,1,2,3,0,3,1,0,0
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,NaN,0,2,1,2,1,3,0,0,1
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,NaN,2,3,3,6,0,6,0,0,1
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,NaN,3,0,1,1,0,1,1,0,0
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,NaN,3,0,0,0,0,0,1,0,0

In [24]:
# Which referees give the most cards?
referee_analysis = (
    df_premier
    .groupby("Referee")
    .agg(
        Games=("Referee", "count"),
        Avg_Goals=("Total_Goals", "mean"),
        Avg_Yellow_Cards=("Total_Yellow_Cards", "mean"),
        Avg_Red_Cards=("Total_Red_Cards", "mean"),
        Avg_Total_Cards=("Total_Cards", "mean"),
        Home_Win_Rate=("Home_Win", "mean"),
        Away_Win_Rate=("Away_Win", "mean"),
        Draw_Rate=("Draw", "mean")
    )
    .reset_index()
)

referee_analysis.sort_values(
    "Avg_Total_Cards",
    ascending=False
)

,Referee,Games,Avg_Goals,Avg_Yellow_Cards,Avg_Red_Cards,Avg_Total_Cards,Home_Win_Rate,Away_Win_Rate,Draw_Rate
24,M Donohue,5,3.000000,5.600000,0.000000,5.600000,0.200000,0.800000,0.000000
32,R Madley,2,3.000000,4.500000,0.500000,5.000000,0.000000,0.000000,1.000000
28,O Oliver,1,1.000000,5.000000,0.000000,5.000000,1.000000,0.000000,0.000000
39,S Singh,1,2.000000,5.000000,0.000000,5.000000,0.000000,0.000000,1.000000
34,S Allison,4,3.750000,4.750000,0.000000,4.750000,0.250000,0.500000,0.250000
33,R Welch,2,2.000000,4.000000,0.500000,4.500000,0.000000,0.500000,0.500000
13,J Brooks,74,2.635135,4.324324,0.121622,4.445946,0.527027,0.243243,0.229730
21,L Smith,10,3.200000,4.100000,0.300000,4.400000,0.500000,0.200000,0.300000
43,T Robinson,49,2.734694,4.163265,0.061224,4.224490,0.489796,0.244898,0.265306
7,D Bond,23,2.826087,4.043478,0.173913,4.217391,0.521739,0.217391,0.260870
17,J Smith,8,3.250000,3.875000,0.250000,4.125000,0.625000,0.125000,0.250000
9,D England,99,3.000000,3.989899,0.111111,4.101010,0.424242,0.313131,0.262626
40,T Bramall,52,2.653846,3.903846,0.173077,4.076923,0.480769,0.192308,0.326923
29,P Bankes,115,2.643478,3.939130,0.121739,4.060870,0.539130,0.243478,0.217391
8,D Coote,100,2.650000,3.930000,0.130000,4.060000,0.450000,0.340000,0.210000
35,S Attwell,150,2.953333,3.913333,0.133333,4.046667,0.446667,0.313333,0.240000
3,A Moss,1,1.000000,4.000000,0.000000,4.000000,0.000000,1.000000,0.000000
26,M Salisbury,61,3.311475,3.852459,0.131148,3.983607,0.491803,0.311475,0.196721
31,R Jones,110,2.781818,3.863636,0.100000,3.963636,0.472727,0.290909,0.236364
36,S Barrott,62,3.112903,3.903226,0.048387,3.951613,0.435484,0.338710,0.225806
6,C Pawson,155,2.754839,3.748387,0.103226,3.851613,0.400000,0.361290,0.238710
37,S Hooper,130,3.015385,3.738462,0.076923,3.815385,0.469231,0.276923,0.253846
14,J Gillett,84,3.095238,3.738095,0.047619,3.785714,0.333333,0.452381,0.214286
23,M Dean,78,2.564103,3.628205,0.153846,3.782051,0.410256,0.307692,0.282051
4,A Taylor,206,3.111650,3.626214,0.135922,3.762136,0.388350,0.364078,0.247573
30,P Tierney,140,2.842857,3.571429,0.128571,3.700000,0.400000,0.335714,0.264286
5,C Kavanagh,153,2.647059,3.581699,0.117647,3.699346,0.424837,0.339869,0.235294
41,T Harrington,48,2.750000,3.583333,0.104167,3.687500,0.375000,0.395833,0.229167
10,D Webb,2,4.000000,3.500000,0.000000,3.500000,1.000000,0.000000,0.000000
1,A Madley,131,2.954198,3.351145,0.106870,3.458015,0.419847,0.335878,0.244275
25,M Oliver,194,3.051546,3.309278,0.118557,3.427835,0.412371,0.381443,0.206186
18,K Friend,68,2.735294,3.058824,0.147059,3.205882,0.426471,0.382353,0.191176
42,T Kirk,6,2.000000,2.666667,0.500000,3.166667,0.333333,0.333333,0.333333
0,A Kitchen,6,2.333333,3.166667,0.000000,3.166667,0.500000,0.000000,0.500000
20,L Mason,27,2.666667,2.962963,0.037037,3.000000,0.481481,0.259259,0.259259
19,K Kavanagh,1,3.000000,3.000000,0.000000,3.000000,1.000000,0.000000,0.000000
38,S Scott,1,4.000000,3.000000,0.000000,3.000000,0.000000,0.000000,1.000000
12,G Scott,55,2.654545,2.763636,0.218182,2.981818,0.454545,0.363636,0.181818
16,J Moss,74,2.986486,2.837838,0.108108,2.945946,0.486486,0.324324,0.189189
2,A Marriner,81,2.938272,2.777778,0.086420,2.864198,0.333333,0.395062,0.271605
22,M Atkinson,84,2.547619,2.583333,0.107143,2.690476,0.464286,0.357143,0.178571
11,F Hallam,5,3.400000,2.600000,0.000000,2.600000,0.400000,0.400000,0.200000
15,J Gillett,1,4.000000,2.000000,0.000000,2.000000,1.000000,0.000000,0.000000
27,O Langford,1,2.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000

In [25]:
# Does the referee have an association with goals?
correlation_table = referee_analysis[
    [
        "Avg_Goals",
        "Avg_Yellow_Cards",
        "Avg_Red_Cards",
        "Avg_Total_Cards",
        "Home_Win_Rate",
        "Away_Win_Rate"
    ]
].corr()

correlation_table

,Avg_Goals,Avg_Yellow_Cards,Avg_Red_Cards,Avg_Total_Cards,Home_Win_Rate,Away_Win_Rate
Avg_Goals,1.000000,-0.133234,-0.132809,-0.150537,0.231886,-0.209398
Avg_Yellow_Cards,-0.133234,1.000000,0.070858,0.988303,-0.089758,0.234543
Avg_Red_Cards,-0.132809,0.070858,1.000000,0.222148,-0.250214,0.024085
Avg_Total_Cards,-0.150537,0.988303,0.222148,1.000000,-0.125989,0.232941
Home_Win_Rate,0.231886,-0.089758,-0.250214,-0.125989,1.000000,-0.387539
Away_Win_Rate,-0.209398,0.234543,0.024085,0.232941,-0.387539,1.000000

In [26]:
print(
    "Correlation between total cards and goals:",
    referee_analysis["Avg_Total_Cards"].corr(
        referee_analysis["Avg_Goals"]
    )
)

print(
    "Correlation between yellow cards and goals:",
    referee_analysis["Avg_Yellow_Cards"].corr(
        referee_analysis["Avg_Goals"]
    )
)

print(
    "Correlation between red cards and goals:",
    referee_analysis["Avg_Red_Cards"].corr(
        referee_analysis["Avg_Goals"]
    )
)

Correlation between total cards and goals: -0.15053734322348128
Correlation between yellow cards and goals: -0.1332344555760998
Correlation between red cards and goals: -0.13280921841933555

In [27]:
# Does the referee affect home-team winning?
home_win_analysis = (
    df_premier
    .groupby("Referee")
    .agg(
        Games=("Referee", "count"),
        Home_Wins=("Home_Win", "sum"),
        Away_Wins=("Away_Win", "sum"),
        Draws=("Draw", "sum")
    )
    .reset_index()
)

home_win_analysis["Home_Win_Rate"] = (
    home_win_analysis["Home_Wins"] /
    home_win_analysis["Games"]
)

home_win_analysis["Away_Win_Rate"] = (
    home_win_analysis["Away_Wins"] /
    home_win_analysis["Games"]
)

home_win_analysis["Draw_Rate"] = (
    home_win_analysis["Draws"] /
    home_win_analysis["Games"]
)

home_win_analysis.sort_values(
    "Home_Win_Rate",
    ascending=False
)

,Referee,Games,Home_Wins,Away_Wins,Draws,Home_Win_Rate,Away_Win_Rate,Draw_Rate
28,O Oliver,1,1,0,0,1.000000,0.000000,0.000000
19,K Kavanagh,1,1,0,0,1.000000,0.000000,0.000000
15,J Gillett,1,1,0,0,1.000000,0.000000,0.000000
10,D Webb,2,2,0,0,1.000000,0.000000,0.000000
17,J Smith,8,5,1,2,0.625000,0.125000,0.250000
29,P Bankes,115,62,28,25,0.539130,0.243478,0.217391
13,J Brooks,74,39,18,17,0.527027,0.243243,0.229730
7,D Bond,23,12,5,6,0.521739,0.217391,0.260870
0,A Kitchen,6,3,0,3,0.500000,0.000000,0.500000
21,L Smith,10,5,2,3,0.500000,0.200000,0.300000
26,M Salisbury,61,30,19,12,0.491803,0.311475,0.196721
43,T Robinson,49,24,12,13,0.489796,0.244898,0.265306
16,J Moss,74,36,24,14,0.486486,0.324324,0.189189
20,L Mason,27,13,7,7,0.481481,0.259259,0.259259
40,T Bramall,52,25,10,17,0.480769,0.192308,0.326923
31,R Jones,110,52,32,26,0.472727,0.290909,0.236364
37,S Hooper,130,61,36,33,0.469231,0.276923,0.253846
22,M Atkinson,84,39,30,15,0.464286,0.357143,0.178571
12,G Scott,55,25,20,10,0.454545,0.363636,0.181818
8,D Coote,100,45,34,21,0.450000,0.340000,0.210000
35,S Attwell,150,67,47,36,0.446667,0.313333,0.240000
36,S Barrott,62,27,21,14,0.435484,0.338710,0.225806
18,K Friend,68,29,26,13,0.426471,0.382353,0.191176
5,C Kavanagh,153,65,52,36,0.424837,0.339869,0.235294
9,D England,99,42,31,26,0.424242,0.313131,0.262626
1,A Madley,131,55,44,32,0.419847,0.335878,0.244275
25,M Oliver,194,80,74,40,0.412371,0.381443,0.206186
23,M Dean,78,32,24,22,0.410256,0.307692,0.282051
30,P Tierney,140,56,47,37,0.400000,0.335714,0.264286
6,C Pawson,155,62,56,37,0.400000,0.361290,0.238710
11,F Hallam,5,2,2,1,0.400000,0.400000,0.200000
4,A Taylor,206,80,75,51,0.388350,0.364078,0.247573
41,T Harrington,48,18,19,11,0.375000,0.395833,0.229167
2,A Marriner,81,27,32,22,0.333333,0.395062,0.271605
14,J Gillett,84,28,38,18,0.333333,0.452381,0.214286
42,T Kirk,6,2,2,2,0.333333,0.333333,0.333333
34,S Allison,4,1,2,1,0.250000,0.500000,0.250000
24,M Donohue,5,1,4,0,0.200000,0.800000,0.000000
32,R Madley,2,0,0,2,0.000000,0.000000,1.000000
33,R Welch,2,0,1,1,0.000000,0.500000,0.500000
27,O Langford,1,0,0,1,0.000000,0.000000,1.000000
38,S Scott,1,0,0,1,0.000000,0.000000,1.000000
39,S Singh,1,0,0,1,0.000000,0.000000,1.000000
3,A Moss,1,0,1,0,0.000000,1.000000,0.000000

In [28]:
print(
    "Referee average goals vs home win rate:",
    referee_analysis["Avg_Goals"].corr(
        referee_analysis["Home_Win_Rate"]
    )
)

print(
    "Referee average cards vs home win rate:",
    referee_analysis["Avg_Total_Cards"].corr(
        referee_analysis["Home_Win_Rate"]
    )
)

Referee average goals vs home win rate: 0.23188611177650661
Referee average cards vs home win rate: -0.12598940155682034

In [29]:
# Does the referee give more cards to the losing team?
def losing_team_cards(row):
    if row["FTR"] == "H":
        return row["Away_Cards"]
    elif row["FTR"] == "A":
        return row["Home_Cards"]
    else:
        return np.nan

def winning_team_cards(row):
    if row["FTR"] == "H":
        return row["Home_Cards"]
    elif row["FTR"] == "A":
        return row["Away_Cards"]
    else:
        return np.nan

df_premier["Winning_Team_Cards"] = df_premier.apply(
    winning_team_cards,
    axis=1
)

df_premier["Losing_Team_Cards"] = df_premier.apply(
    losing_team_cards,
    axis=1
)

/var/folders/dz/y62g61hn65n3bj60zmb7ppf00000gn/T/ipykernel_2157/1481822262.py:18: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

/var/folders/dz/y62g61hn65n3bj60zmb7ppf00000gn/T/ipykernel_2157/1481822262.py:23: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

In [30]:
print(
    "Average cards for winning team:",
    df_premier["Winning_Team_Cards"].mean()
)

print(
    "Average cards for losing team:",
    df_premier["Losing_Team_Cards"].mean()
)

Average cards for winning team: 1.6843919251600197
Average cards for losing team: 1.9566715903495815

In [31]:
# Does referee identity predict the match result?
fig = px.bar(
    home_win_analysis.sort_values("Home_Win_Rate", ascending=False),
    x="Referee",
    y="Home_Win_Rate",
    title="Home-Team Win Rate by Referee",
    labels={
        "Home_Win_Rate": "Home Win Rate"
    }
)

fig.show()

In [32]:
fig = px.bar(
    home_win_analysis.sort_values("Away_Win_Rate", ascending=False),
    x="Referee",
    y="Away_Win_Rate",
    title="Away-Team Win Rate by Referee",
    labels={
        "Away_Win_Rate": "Away Win Rate"
    }
)

fig.show()

In [34]:
import numpy as np
import plotly.graph_objects as go

x = referee_analysis["Avg_Total_Cards"]
y = referee_analysis["Avg_Goals"]

# Calculate trendline
slope, intercept = np.polyfit(x, y, 1)

# Predicted values
y_pred = slope * x + intercept

fig = go.Figure()

# Scatter points
fig.add_trace(go.Scatter(
    x=x,
    y=y,
    mode="markers",
    text=referee_analysis["Referee"],
    marker=dict(
        size=referee_analysis["Games"] / 5
    ),
    hovertemplate=(
        "<b>%{text}</b><br>"
        "Average Cards: %{x:.2f}<br>"
        "Average Goals: %{y:.2f}"
        "<extra></extra>"
    ),
    name="Referees"
))

# Trendline
fig.add_trace(go.Scatter(
    x=x,
    y=y_pred,
    mode="lines",
    name="Trend Line"
))

fig.update_layout(
    title="Referee Cards vs. Average Goals Scored",
    xaxis_title="Average Total Cards per Match",
    yaxis_title="Average Goals per Match"
)

fig.show()

In [35]:
correlation = referee_analysis["Avg_Total_Cards"].corr(
    referee_analysis["Avg_Goals"]
)

print("Correlation between referee cards and goals:", correlation)

Correlation between referee cards and goals: -0.15053734322348128

In [36]:
r_squared = correlation ** 2

print("Correlation:", correlation)
print("R²:", r_squared)

Correlation: -0.15053734322348128
R²: 0.022661491704784206