In [2]:
import pandas as pd

In [3]:
url = 'https://raw.githubusercontent.com/kkathait/D501_Final_Project/refs/heads/main/combined_data.csv'

df_premier = pd.read_csv(url)

In [6]:
teams = sorted(set(df_premier["HomeTeam"]) | set(df_premier["AwayTeam"]))

records = []

for team in teams:
    home_games = df_premier[df_premier["HomeTeam"] == team]
    
    home_wins = (home_games["FTR"] == "H").sum()
    home_losses = (home_games["FTR"] == "A").sum()
    home_draws = (home_games["FTR"] == "D").sum()
    
    away_games = df_premier[df_premier["AwayTeam"] == team]
    
    away_wins = (away_games["FTR"] == "A").sum()
    away_losses = (away_games["FTR"] == "H").sum()
    away_draws = (away_games["FTR"] == "D").sum()
    
    records.append({
        "Team": team,
        "Wins": home_wins + away_wins,
        "Losses": home_losses + away_losses,
        "Draws": home_draws + away_draws
    })

standings = pd.DataFrame(records)

standings = standings.sort_values("Wins", ascending = False)

standings

                Team  Wins  Losses  Draws
15          Man City   182      41     43
13         Liverpool   165      43     58
0            Arsenal   154      56     56
16        Man United   127      74     65
6            Chelsea   123      77     66
23         Tottenham   115      99     52
1        Aston Villa   114      99     53
17         Newcastle   107      96     63
26          West Ham    91     114     61
4           Brighton    90      89     87
8            Everton    86     110     70
7     Crystal Palace    82     103     81
27            Wolves    81     124     61
3          Brentford    68      73     49
12         Leicester    67      85     38
9             Fulham    63      83     44
2        Bournemouth    61      78     51
19     Nott'm Forest    48      65     39
11             Leeds    45      67     40
21       Southampton    44     106     40
5            Burnley    41      98     51
20  Sheffield United    24      69     21
24           Watford    14      47     15
22        Sunderland    14      12     12
18           Norwich    10      53     13
14             Luton     6      24      8
25         West Brom     5      22     11
10           Ipswich     4      24     10

In [8]:
standings["Points"] = (3 * standings["Wins"]) + standings["Draws"]

standings["Games"] = (standings["Wins"] + standings["Losses"] + standings["Draws"])

standings = standings.sort_values("Games", ascending = False)

standings

                Team  Wins  Losses  Draws  Points  Games
15          Man City   182      41     43     589    266
13         Liverpool   165      43     58     553    266
0            Arsenal   154      56     56     518    266
16        Man United   127      74     65     446    266
6            Chelsea   123      77     66     435    266
23         Tottenham   115      99     52     397    266
1        Aston Villa   114      99     53     395    266
17         Newcastle   107      96     63     384    266
4           Brighton    90      89     87     357    266
26          West Ham    91     114     61     334    266
8            Everton    86     110     70     328    266
7     Crystal Palace    82     103     81     327    266
27            Wolves    81     124     61     304    266
3          Brentford    68      73     49     253    190
12         Leicester    67      85     38     239    190
2        Bournemouth    61      78     51     234    190
9             Fulham    63      83     44     233    190
5            Burnley    41      98     51     174    190
21       Southampton    44     106     40     172    190
19     Nott'm Forest    48      65     39     183    152
11             Leeds    45      67     40     175    152
20  Sheffield United    24      69     21      93    114
24           Watford    14      47     15      57     76
18           Norwich    10      53     13      43     76
22        Sunderland    14      12     12      54     38
14             Luton     6      24      8      26     38
25         West Brom     5      22     11      26     38
10           Ipswich     4      24     10      22     38